### ISSUE TITLE
Command line calls to ffmpeg?

### ISSUE THREAD

**Issue by Rodeoclash** [milworm/media-recorder-demo#1]
Your project is something quite similar to what we're trying to do, using ffmpeg via nacl.

This call here:
https://github.com/milworm/media-recorder-demo/blob/master/new/background.js#L141

How are you passing that to the nacl module? I can't see any *.cc files in your project that might be receiving it.

**Comment by milworm** [comment]
@rodeoclash
You don't need any *.cc files. I use that line here: https://github.com/milworm/media-recorder-demo/blob/master/new/background.js#L168

In this case you end up with something like:
<embed arg0="firstArg" arg1="secondArg" ...></embed>

**Comment by Rodeoclash** [comment]
Ah, so the pexe you built basically mimics ffmpegs command line interface? Did you have to configure a virtual file system etc for it or did you just use the naclports / webports ffmpeg out of the box without modification?

**Comment by milworm** [comment]
I didn't build it, but yes in order to use it you need to configure a virtual file system.

**Comment by Rodeoclash** [comment]
Alright, thanks for the help :)

**Comment by preetampvp** [comment]
@milworm: Hi.. just a few questions.

I tried loading the pexe in your repo and just passed "ffmpeg" and "-h" as args to embed.. I can see the pnacl loading (listening to the load events in js).. but once the loading is done it crashes.. just wondering should ffmpeg -h work?.. also if you know if there is a way to find out what caused the crash?

Also in the code you are adding an attribute to redirect ps_std\* to /dev/tty... how can I view the redirected messages? Or is this accessible only when you debug the pnacl?

Thanks in advance.

**Comment by milworm** [comment]
just wondering should ffmpeg -h work - haven't tested, but maybe it's normal that it doesn't work.
how can I view the redirected messages? Or is this accessible only when you debug the pnacl? -
yes, I think it's accessible only when you debug it.

also if you know if there is a way to find out what caused the crash - unfortunately no :( and .. this was one of the reasons why I stopped doing recording with pnacl, chrome now supports MediaRecorder API, so you can just use it instead. 
I have a blog post about this (if you are interested) https://60devs.com/recording-videos-in-the-browser-using-media-recorder-api.html

plus you can check my branch:
https://github.com/milworm/media-recorder-demo/tree/release-native

the code is clean and it works without NACL/PNACL

**Comment by preetampvp** [comment]
Thanks for the quick response.. will take a look :)

**Comment by Rodeoclash** [comment]
@milworm We got it working in the end. Thanks for your help! Another question, who built the c/c++ code that generated the pexe?

**Comment by milworm** [comment]
No problem, I took it from this website:
http://neo.idletime.tokyo/enu/ffmpeg_pnacl/

**Comment by Rodeoclash** [comment]
Awesome thanks!

**Comment by preetampvp** [comment]
**_Sending pp_std\* from pnacl to browser_** -  Using _/dev/console3_ instead of _/dev/tty_ ... std\* will redirect messages to browser console.. This is how we figured out what was causing the pnacl to crash  - hope someone finds it handy someday :-)
